
						andiUA.TUAsettingFn = {
						andiconnnectserver:1,
						TUAshowIframeErrors :0,
						TUAmaxFontsSize :1.3,
						compenyname:"אריק",
						compenywebsite:"",
						TUAjsPath:andiUA.jsPath,
						TUAimgPath:andiUA.jsPath,
						TUA2skipAreaAutomate:false,
						TUAfindjsevents:0,
						TUAElms: ('*'),
						TUAallFocsuElms: ('[role="link"],[role="button"],a, area, input, select, textarea, button, *[tabindex], *[contenteditable]'),
						TUAallFocsuElmsStyle: ('outline'),
						TUAallButtons: ('select,option,textarea,button,[role="button"], .active, :active , input'),
						TUAallHeading: ('a ,a *,h1 ,h2 ,h3 ,h4 ,h5 ,h6 ,h1 *,h2 *,h3 *,h4 *,h5 *,h6 *,[role="heading"],[role="heading"] *'),
						TUAjustBtns: ('button,[role="button"],[type="button"],[type="submit"],[type="image"]'),
						TUAallImg:'img,[role="img"],svg',
						TUAMagnifyingGlassSizeText:28,
						TUAflashElms:'object , embed',
						TUAreadMoreHeadign:'h1,h2,h3,h4,h5,h6,[role="heading"],[class*="title"]',
						TUAreadMoreLastLinkOrBtn:'a,[role="link"]',
						TUAmeaningElmsList :'div,span,button,input[type="button"],a',
						TUAmainLang:'',
						TUAfontSizeException : (''),
						TUATUABGcolorException:(''),
						TUAmakeCssFocusFromHOver: false,
						TUAactiveFixFlash: false,
						TUAhideCopyRight :false,
						TUAremoveLinkToAndi :false,
						TUAremoveLogo :false,
						TUApresentationTables :true,
						TUApresentationTablesException :'',
						TUAremoveBackGroundImgInHighContrast :false,
						TUAremoveImgInHighContrast :false,
						TUAsetMenuLogo :'4',
						TUAmenuIconIsFixed :true,
						TUAaccessibleTitleForKeyboardUser :false,
						TUAaccessibleTitleForKeyboardUserIframe :1,
						TUAimgToGray :false,
						TUAsiteDesciption :'',
					TUAparam : {
						backgroundColor: '#242c4f',
						TUAtextColor:'#000',
						TUAmenuOpenTo:'left',
						TUAourIconWidth: 35,
						TUAourIconHeight: 35,
						TUAAccessibilityBarItems: '#ANDISELECTORopenSetItAccessibilityBar *',
						TUAiconPositionRightOrLeft320: 'left',
						TUAourIconPositionFromTop320:10,
						TUAourIconPositionFromSide320:10,
						TUAiconPositionRightOrLeft480:'left',
						TUAourIconPositionFromTop480 :10,
						TUAourIconPositionFromSide480:10,
						TUAiconPositionRightOrLeft767 : 'left',
						TUAourIconPositionFromTop767:10,
						TUAourIconPositionFr54e767: 10,
						TUAiconPositionRightOrLeft960: 'left',
						TUAourIconPositionFromTop960 :10,
						TUAourIconPositionFromSide960 :10,
						TUAiconPositionRightOrLeft1024 :'left',
						TUAourIconPositionFromTop1024 :10,
						TUAourIconPositionFromSide1024 :10,
						TUAiconPositionRightOrLeft1280 :'left',
						TUAourIconPositionFromTop1280 :10,
						TUAourIconPositionFromSide1280 :10
					},
					
				TUABackgroundImages : [],
				TUAhidearea : [],
				TUAhideformsr : [],
				TUAfixedcontenttable : [],
				TUAuserSlider : [],
				TUAlinkText : [{
						TUAelm :'.btn-search-reset',
						TUAtext:'reset',
						TUArunOnPc:true,
						TUArunOnMobile:true}],
				TUAareaLinks : [],
				TUAbuttuns : [],
				TUAaccMenus : [],
				TUAsetAsArticle : [],
				TUAfUserLightBox : [],
				TUAuserDatePicker : [],
				TUAdynamicLoad : [],TUAaltForImgs : [],
				TUAsetAsHeader : [],
				TUAforceTitleToInputSetting : [],
				TUAautomaticValidationForm : [{
						TUARightOrLeft :'left',
						TUAfromSizeP :10,
						TUAfromTopP :10,
						TUAinputTypes :'input,textarea',
						TUAinputTypesRadioAndCheckbox :'',
						TUAwidthErrorContainer :300,
						TUArunOnPc:true,
						TUArunOnMobile:true}],
				TUACheckbox : [],
				TUApagesNavigation : [],
				TUApagesNavigation : [],
				TUAFaQComponents : [],
				TUAhideElmsINPCMode : [],
				TUABreadcrumbs : [],
				TUAaccessibilityStatement : [{
								TUAStatementText :'		<h2>קצת רקע</h2><p>על מנת לאפשר לאנשים עם מוגבלויות את האפשרות לגלוש באינטרנט בצורה חלקה, ממש כמו כל אחד אחר, השקענו מאמצים אדירים בבניית טכנולוגיה מתקדמת שתאפשר לבעלי אתרים להנגיש את האתר שלהם לשימושם של אנשים עם מוגבלויות ולחשוף את המידע הקיים באתר לאוכלוסייה חשובה נוספת.</p>		<p>האתר מתחייב לספק לקהל הרחב הגולש באתר, תוכן נגיש ככל שניתן, ללא כל קשר לטכנולוגיה בה נבנה האתר. אנחנו פועלים לעדכן ולהטמיע את כללי הנגישות ככל שניתן, בהתאם לעקרונות תקן הנגישות. האתר מותאם לדרישות הנגישות לרמה 2 (AA) של התקן .W.C.A.G 2 הנגישות באתר מותאמת לדפדפנים המובילים: </p><ul><li>כרום.</li> <li>פיירפוקס. </li><li>אקספלורר 11 ומעלה. </li><li>אופרה.</li></ul>		<h2>שימוש ב Andi UA</h2><p>התפריט של אנדי ( שמתם לב לדמות הקטנה בלוגו ? קוראים לה אנדי. ) יודע לעבוד עם הדפדפנים המובילים:</p><p>כרום, פיירפוקס ,אקספלורר 11 ומעלה ,אופרה.</p>		<h2>תמיכה בטכנולוגיות מסיעות</h2><p>אנדי תומך בטכנולוגיות מסייעות על ידי שימוש בחוקי ARIA.</p>		<h2>איך משתמשים ברכיב אנדי ?</h2><p>הטכנולוגיה של Andi UA פועלת במספר מישורים כדי לאפשר להנגשה מקסימלית של האתר, הן באמצעות תפריט נגישות והן באמצעות התממשקות לרכיבים שונים באתר.</p><p>באתר מוצב תפריט הנגשה. כדי לפתוח את התפריט תוכל ללחוץ על האייקון הממוקם בחלקו העליון של האתר  או ללחוץ במקלדת על כפתור "F10". כדי לסגור את התפריט תוכל ללחוץ על הכפתור הסגירה או ללחוץ במקלדת על כתפור "ESC". F1 לכדי לחזור לדף זה מכל מקום באתר.</p><p>בכניסתך בפעם הראשונה לתפריט תוכל לבחור את שפת הממשק, התומך בריבוי שפות, וגודל התצוגה הרצוי לך. בכל שלב תוכל לשנות את הגדרותיך בפתור ההגדרות הממוקם בראש התפריט.</p><p>לחיצה על כפתור "הפעלת הנגישות" תעביר אותך את תפריט הנגישות המורכב משני חלקים: </p>		<h2>תפריט ראשי</h2>		<h3>גודל טקסט</h3><p>מאפשר לבחור ולשנות את גודל הטקסט המופיע באתר, באמצעות זכוכית מגדלת המעניקה הגדלה מקומית, נקודתית בשליטת הגולש ו/או באמצעות הגדלה והקטנה אוטומטיים של הטקסט בכל האתר, בלחיצת כפתור.</p>		<h3>צבעים</h3><p>מאפשר לבחור ולשנות את צבעי האתר וליצור התאמה אישית מתוך סט צבעים, באמצעות שינוי של צבעי הרקע של האתר, הכותרות באתר או הטקסט באתר, או לחילופין, שינוי הניגודיות בכל האתר, בלחיצת כפתור.</p><h4>כיצד לבצע את ההתאמה האישית?</h4><p>לאחר בחירת צבע הרקע, הכותרות או הטקסט יש לאשר את הבחירה באמצעות לחיצה על V, ולאחר מכן הצבע הנבחר יסומן בצידו הימני של ריבוע הבחירה.</p>		<h3>נגישות עכבר </h3><p>מאפשר שינוי צבע סמן העכבר לשחור או לבן. </p>		<h3>מציאת העכבר </h3><p>ניתן לאתר את מיקום העכבר במסך, על ידי לחיצה על כפתור ה "CTRL".</p>		<h3>הדגשת קישור בקו תחתון </h3><p>מאפשר איתור קישורים באתר שלא רק באמצעות צבע הקישור, אלא על ידי הדגשת הקישור באמצעות קו תחתון.</p>		<h3>שנה גופן לקריא יותר </h3><p>גופן ARIEL נקבע כגופן הקריא ביותר בהתאם לתקנות הנגישות. כפתור המרת הגופן, מאפשר לבעל האתר לשמור על חופש העיצוב בבחירת הגופנים באתר תוך מתן הבחירה לאדם בעל המוגבלויות לשנות את הגופן ל ARIEL בכל האתר בלחיצת כפתור.</p>		<h3>הדלקת תפריט נגישות בקליק ימני בעכבר </h3><p>הפעלת כפתור זה,  משנה את הגדרות הכפתור הימני בעכבר, כך שלחיצה עליו בכל מקום באתר תפעיל תפריט נגישות מקוצר של הפעולות המרכזיות. ניתן לבטל פונקציה זו בצידו השמאלי התחתון של התפריט, שנפתח בלחיצה על הכפתור הימני בעכבר.</p>		<h3>איפוס כל ההתאמות </h3><p>מחזיר את האתר להגדרות ברירת המחדל.</p>		<h3>הצהרת נגישות </h3><p>ניתן להגיע למסמך זה ע"י לחיצה על F1 במקלדת</p>		<h3>הצעות ייעול </h3><p>בתחתית התפריט מופיע אייקון מנורה הפותח טופס למתן משוב והצעות ייעול להנגשת האתר. המשוב שלכם חשוב לנו לצורך שיפור יכולות הנגישות.</p>		<h2>תפריט אזור אישי (גרסת אנדי יו בלבד)</h2><p>תפריט זה מאפשר, באמצעות לימוד הרגלי הגלישה של המשתמש, שימוש נגיש יותר באתר.</p>		<h3>המשך גלישה מהמקום הקודם בו הפסקת גלישה </h3><p>מאפשר לגולש לחזור למקום האחרון בו הפסיק את גלישתו באתר בביקור האחרון שלו.</p>		<h3>הוסף דף זה למועדפים</h3><p>מאפשר לגולש להוסיף את העמוד הספציפי בתוך האתר לרשימת מועדפים פנימית של האתר עצמו כדי שיוכל לחזור לעמודים שהוא אוהב בגלישות הבאות.</p>		<h3>הצגת רשימת המועדפים</h3><p> מציג את רשימת הדפים שבחרת.</p>		<h2>בחלק מהאתרים מותקנות אפשרויות נוספות כגון:</h2>		<h3>תמיכה מלאה בניווט מקלדת</h3>		<h4>תמיכה בניווט מהיר בין אזורים</h4><p>האתר מחולק לאזורים כגון אזור תוכן מרכזי או אזור תפריט צדדי. בתחילת כל אזור ישנה כותרת ברמה 3, המציינת את שמו של האזור אליו הגעתם. חלק מהכותרות הם גם לינקים המשמשים אתכם לדילוג מעל אותו אזור ובכך יסייעו לכם להגיע מהר יותר אל התוכן המבוקש. לדוגמה ישנה אפשרות לדלג אל התוכן המרכזי מראש הדף.</p>		<h4>שינוי צבע הפוקוס בהתאם לרקע.</h4>		<h4>מקלדת וירטואלית עבור מילוי טפסים </h4><p>ניתן להציג מקלדת וירטואלית לצורך הגדלה בעזרת העכבר.</p>		<h4>הסתרת הסמן עכבר בעת הקלדה</h4><p>במידה וסמן העכבר נמצא על שדה הטופס בעת הקלדת אנדי ידאג להסתיר אותו עד שתסיימו להקליד.</p>		<h4>ניווט מהיר בין ראשי פרקים במאמר </h4><p>מאפשר פתיחת תפריט בראש המאמר המציג את ראשי הפרקים שבו ומאפשר הבנה מהירה של מבנה המאמר ורלוונטיות התוכן בו עבורי וכן דילוג ישירות לחלק ספציפי בתוך המאמר.</p>		<p>לנוחיותכם להלן פירוט קיצורי מקלדת:</p><p>F1 – עזרה והצהרת נגישות.<br/>F3 – חיפוש בדף<br/>F6 – חזרה לשורת הכתובת (URL).<br/>F5 – רענון של הדף האינטרנט.<br/>F10 – פתיחה / סגירה של תפריט הנגישות.<br/>ESC – ביטול.<br/>חץ למטה – גלילה רגילה למטה.<br/>חץ למעלה – גלילה רגילה למעלה.<br/>Page Down , רווח – גלילה של מסך למטה<br/>Shift + רווח   Page up , – גלילה של מסך למעלה.<br/>אנטר – אישור / הפעלה של קישורים וכפתורים<br/>TAB – ניווט  בין קישורים , כפתורים, ושדות בטפסים.<br/>SHIFT + TAB – ניווט אחורה בין קישורים כפתורים ושדות בטפסים. <br/>BACKSPACE  - מחיקה של טקסט שנמצא מאחורי הסמן.<br/>DELETE – מחיקה של טקסט שנמצא לפני הסמן.<br/>חץ שמאלה + alt  - חזרה לעמוד האחרון שגלשנו.<br/></p>		<h3>כיצד לגלוש באתר בקלות באמצעות קורא מסך?</h3><p>בנוסף לאותם קיצורי מקלדת, משתמשי תוכנות קוראי מסך יכולים להעזר בקיצורים הבאים:  (נכון לרב תוכנות קוראי מסך)</p>		<p>K – מעבר בין קישורים <br/>L – מעבר בין רשימות בדף<br/>I – מעבר בין פריטים ברשימה.<br/>F – מעבר בין שדות של טפסים וכפתורים.<br/>T -מעבר בין טבלאות בדף<br/>H – מעבר בין כותרות.<br/>1 – מעבר בין כותרות רמה 1<br/>2 – מעבר בין כותרות רמה 2<br/>3 – מעבר בין כותרות רמה 3<br/>4 – מעבר בין כותרות רמה 4<br/>5 – מעבר בין כותרות רמה 5<br/>6 – מעבר בין כותרות רמה 6<br/></p>		<h3>הנגשת טפסים</h3><p>ישנה תמיכה רחבה בטפסים עבור טכנולוגיות מסייעות. לדוגמה: תמיכה בהקראת שגיאות על ידי תוכנות קוראות מסך.</p>		<h3>הנגשת התפריטים</h3><p>ניתן לנווט בעזרת המקלדת או קורא מסך בקלות ולהגיע גם לתתי התפריט.</p>		<h3>הוספת תמיכה מאפיין הטייטל (טול טיפ) עבור משתמשי מקלדת</h3><p>המידע של הטול טיפ  מופיע גם כאשר מנווטים בעזרת מקלדת.</p>		<h3>תמיכה בסליידרים (שקופיות מתחלפות ) </h3><p>בכל סליידר ישנו כפתור שמקל על החלפת השקופיות עבור משתמשי מקלדת ומשתמשי תוכנות קוראות מסך ע"י פריסה של השקופיות אחת מתחת לשני. בעת הלחיצה על הכפתור יופיע פס גלילה לצידו וניתן לגלול בעזרת החצים או לעבור משקופית לשקופית ע"י לחיצה על טאב במקלדת. </p>		<h3>מעט מהרשימה הארוכה שאנדי יודע להנגיש ...</h3><p>טיפול בלינקים ריקים<br/>הגדרת כפתורים וחיווי עבור עיוורים<br/>תמיכה תגית BR (שבירת שורה) עבור עיוורים<br/>תמיכה בהודעות עבור עיוורים<br/>סידור היררכית כותרות<br/>התרעות עבור פתיחת דף חדש , סוגי קבצים , קבצים להורדה<br/>תמיכה ברכיבי טאבים<br/>תמיכה בלייטבוקס<br/>ועוד...</p>		<h2>בעיות קיימות</h2><p>לא ידועות בעיות כרגע</p>		<h2>נתקלת בבעיה ?</h2><p>ספרו לנו! אנחנו משתדלים לשמור ולתחזק את האתר ברמה הטובה ביותר. במידה ומצאת ו/או נתקלת בקשיים בגלישה באתר ובנושא הנגישות בפרט, אל תהססו לדווח באמצעות טופס צור קשר . כדי שנוכל לטפל בבעיה בדרך הטובה ביותר בבקשה צרפו פרטים מלאים ככל שניתן:</p><p>תיאור הבעיה.<br/>מהי הפעולה שניסיתם לבצע?<br/>באיזה דף גלשתם?<br/>סוג וגרסה של הדפדפן.<br/>מערכת הפעלה וגרסתה.<br/>סוג הטכנולוגיה המסייעת (במידה והשתמשתם).<br/></p><p><b>אנחנו נטפל בבעיה ונחזור אליך בהקדם עם פרטים על טיפולה.</b></p>		<h2>הצעות לשיפור</h2><p>נשמח לשמוע ממכם כיצד ניתן לשפר את אנדי. שלחו אלינו את ההצעות שלכם ואנחנו נבחן אותם בקיפדה. כתובת המייל למשלוח הצעות היא: info@user-a.co.il</p>		<h2>לתשומת ליבכם</h2><p>במהלך הגלישה באתר יתכן ותיתקלו בדף / חלק שטרם הונגש באופן מספק. </p>',
								CustomerEmail :'info@shop4all.co.il',
								LinkToContactUs :'https://www.shop4all.co.il/contact-us-%D7%A6%D7%95%D7%A8-%D7%A7%D7%A9%D7%A8/',
								TUArunOnPc:true,
								TUArunOnMobile:true}],
					};
					andiUA.TUAcustomCodeBefore = function(){ };
					andiUA.TUAcustomCodeAfter = function(){ };
				andiUA.loadCodeDynamicAfter = function(){};
				andiUA.TUAoneTimeCustomCodeAfter = function(){};
				andiUA.TUAaddCustomCss = function() { var ANDIcss = ' #TUAAndiIconOpenMenuBtn, #TUAsetItAccessible { top: auto !important;  right:auto  !important; left: 10px  !important;  bottom: 5% !important;} '; if(ANDIcss != ''){ UA1("head").appendHtml('<style id="TUAaddCustomCss">'+ANDIcss+'</style>'); } };
				localStorage.setItem('groupID','208035788');
				localStorage.setItem('client_id','\'1286\'');
				